Add data source tenant
goauthentik/terraform-provider-authentik pull request #217
Opened 2022-07-20 12:38 UTC by l-with

add data source tenant to make it easier to create a replicate from a tenant with some identical values

2022-07-20 16:46 UTC, l-with commented
> Looks good, thanks! Can you rebase on master/fix that typo in stage.md?

I am confused: this is link to the template on the commit "Bump github.com/hashicorp/terraform-plugin-sdk/v2 from 2.18.0 to 2.19…", commit id 21b18db: https://github.com/goauthentik/terraform-provider-authentik/blob/21b18dbc7bc4b8f1e55a2385baa279a25f0ced34/templates/data-sources/stage.md.tmpl

The main branch also contains the typo again, the interesting thing is that the commit history of the file only mentions the fix of the typo.

I explain that just to inform you about the weird git history.

I suggest that I fix the typo again in this mr.

2022-07-22 08:52 UTC, BeryJu requested changes

2022-07-22 08:52 UTC, BeryJu commented on docs/data-sources/stage.md
> +# To get the ID of a stage by bame
missing a `make`

2022-07-22 12:13 UTC, l-with commented on docs/data-sources/stage.md
> +# To get the ID of a stage by bame
ups, sorry

2022-07-22 14:04 UTC, merged